apiVersion: v1
kind: Secret
metadata:
  name: ums-secrets
  namespace: ums
type: Opaque
stringData:
  APP_KEY: "${APP_KEY}"
  DB_HOST: "${DB_HOST}"
  DB_DATABASE: "${DB_DATABASE}"
  DB_USERNAME: "${DB_USERNAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  REDIS_HOST: "${REDIS_HOST}"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  REDIS_PORT: "${REDIS_PORT}"
  JWT_SECRET: "${JWT_SECRET}"
  ELASTICSEARCH_HOST: "${ELASTICSEARCH_HOST}"
